<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cam_Mode_2 extends Model
{
    use HasFactory;
    protected $table = "cam_mode_2";

    protected $primaryKey = "id";

    public $incrementing = true;

    protected $fillable = [
        'Cam_Mode[6]_Name',
        'Cam_Mode[6]_Width',
        'Cam_Mode[6]_Height',
        'Cam_Mode[6]_XScale',
        'Cam_Mode[6]_XOffset',
        'Cam_Mode[6]_YScale',
        'Cam_Mode[6]_YOffset',
        'Cam_Mode[6]_FusionMode',
        'Cam_Mode[6]_Bin44',
        'Cam_Mode[6]_RoiU',
        'Cam_Mode[6]_RoiV',
        'Cam_Mode[6]_Rotation',
        'Cam_Mode[6]_RoiWidth',
        'Cam_Mode[6]_RoiHeight',
        'Cam_Mode[6]_TimeErrorConst_ms',
        'Cam_Mode[6]_TimeErrorVCoef_ms',
        'Cam_Mode[7]_Name',
        'Cam_Mode[7]_Width',
        'Cam_Mode[7]_Height',
        'Cam_Mode[7]_XScale',
        'Cam_Mode[7]_XOffset',
        'Cam_Mode[7]_YScale',
        'Cam_Mode[7]_YOffset',
        'Cam_Mode[7]_FusionMode',
        'Cam_Mode[7]_Bin44',
        'Cam_Mode[7]_RoiU',
        'Cam_Mode[7]_RoiV',
        'Cam_Mode[7]_Rotation',
        'Cam_Mode[7]_RoiWidth',
        'Cam_Mode[7]_RoiHeight',
        'Cam_Mode[7]_TimeErrorConst_ms',
        'Cam_Mode[7]_TimeErrorVCoef_ms',
        'Cam_Mode[8]_Name',
        'Cam_Mode[8]_Width',
        'Cam_Mode[8]_Height',
        'Cam_Mode[8]_XScale',
        'Cam_Mode[8]_XOffset',
        'Cam_Mode[8]_YScale',
        'Cam_Mode[8]_YOffset',
        'Cam_Mode[8]_FusionMode',
        'Cam_Mode[8]_Bin44',
        'Cam_Mode[8]_RoiU',
        'Cam_Mode[8]_RoiV',
        'Cam_Mode[8]_Rotation',
        'Cam_Mode[8]_RoiWidth',
        'Cam_Mode[8]_RoiHeight',
        'Cam_Mode[8]_TimeErrorConst_ms',
        'Cam_Mode[8]_TimeErrorVCoef_ms',
        'Cam_Mode[9]_Name',
        'Cam_Mode[9]_Width',
        'Cam_Mode[9]_Height',
        'Cam_Mode[9]_XScale',
        'Cam_Mode[9]_XOffset',
        'Cam_Mode[9]_YScale',
        'Cam_Mode[9]_YOffset',
        'Cam_Mode[9]_FusionMode',
        'Cam_Mode[9]_Bin44',
        'Cam_Mode[9]_RoiU',
        'Cam_Mode[9]_RoiV',
        'Cam_Mode[9]_Rotation',
        'Cam_Mode[9]_RoiWidth',
        'Cam_Mode[9]_RoiHeight',
        'Cam_Mode[9]_TimeErrorConst_ms',
        'Cam_Mode[9]_TimeErrorVCoef_ms',
        'Cam_Mode[10]_Name',
        'Cam_Mode[10]_Width',
        'Cam_Mode[10]_Height',
        'Cam_Mode[10]_XScale',
        'Cam_Mode[10]_XOffset',
        'Cam_Mode[10]_YScale',
        'Cam_Mode[10]_YOffset',
        'Cam_Mode[10]_FusionMode',
        'Cam_Mode[10]_Bin44',
        'Cam_Mode[10]_RoiU',
        'Cam_Mode[10]_RoiV',
        'Cam_Mode[10]_Rotation',
        'Cam_Mode[10]_RoiWidth',
        'Cam_Mode[10]_RoiHeight',
        'Cam_Mode[10]_TimeErrorConst_ms',
        'Cam_Mode[10]_TimeErrorVCoef_ms',
        'Cam_Mode[11]_Name',
        'Cam_Mode[11]_Width',
        'Cam_Mode[11]_Height',
        'Cam_Mode[11]_XScale',
        'Cam_Mode[11]_XOffset',
        'Cam_Mode[11]_YScale',
        'Cam_Mode[11]_YOffset',
        'Cam_Mode[11]_FusionMode',
        'Cam_Mode[11]_Bin44',
        'Cam_Mode[11]_RoiU',
        'Cam_Mode[11]_RoiV',
        'Cam_Mode[11]_Rotation',
        'Cam_Mode[11]_RoiWidth',
        'Cam_Mode[11]_RoiHeight',
        'Cam_Mode[11]_TimeErrorConst_ms',
        'Cam_Mode[11]_TimeErrorVCoef_ms',
        'Cam_Mode[12]_Name',
        'Cam_Mode[12]_Width',
        'Cam_Mode[12]_Height',
        'Cam_Mode[12]_XScale',
        'Cam_Mode[12]_XOffset',
        'Cam_Mode[12]_YScale',
        'Cam_Mode[12]_YOffset',
        'Cam_Mode[12]_FusionMode',
        'Cam_Mode[12]_Bin44',
        'Cam_Mode[12]_RoiU',
        'Cam_Mode[12]_RoiV',
        'Cam_Mode[12]_Rotation',
        'Cam_Mode[12]_RoiWidth',
        'Cam_Mode[12]_RoiHeight',
        'Cam_Mode[12]_TimeErrorConst_ms',
        'Cam_Mode[12]_TimeErrorVCoef_ms',
        'Cam_Mode[13]_Name',
        'Cam_Mode[13]_Width',
        'Cam_Mode[13]_Height',
        'Cam_Mode[13]_XScale',
        'Cam_Mode[13]_XOffset',
        'Cam_Mode[13]_YScale',
        'Cam_Mode[13]_YOffset',
        'Cam_Mode[13]_FusionMode',
        'Cam_Mode[13]_Bin44',
        'Cam_Mode[13]_RoiU',
        'Cam_Mode[13]_RoiV',
        'Cam_Mode[13]_Rotation',
        'Cam_Mode[13]_RoiWidth',
        'Cam_Mode[13]_RoiHeight',
        'Cam_Mode[13]_TimeErrorConst_ms',
        'Cam_Mode[13]_TimeErrorVCoef_ms'
    ];
    
    /**
     * Get the sensor that owns the dsp_parameters.
     */
    public function Sensor()
    {
        return $this->belongsTo(Sensor::class);
    }
}
